# Generated by Django 5.1.4 on 2024-12-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='shop.product', verbose_name='Продукты'),
        ),
    ]
